[package]
name = "rquote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
wasm-bindgen-futures = "0.4.29"
urlencoding = "2.1.0"
async-trait = "0.1.52"
pulldown-cmark = "0.9.1"

[dependencies.web-sys]
version = "0.3.56"
features = [
    "Window",
    "MediaQueryList",
    "Document",
    "HtmlElement",
    "DomTokenList",
    "Element",
    "HtmlCollection"
]

[dependencies.reqwest]
version = "0.11.9"
features = ["json"]


[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
